// Shared product catalog. Both the homepage cards and the product page read from here.
const PRODUCTS = {
  'paris': {
    id: 'paris',
    name: 'Paris',
    tag: 'New Drop',
    price: 169,
    description: 'הדפס "Paris in Nature" — מגדל אייפל עטוף בוורדים לבנים. עיצוב נקי בחזית ויצירה מלאה בגב, על חולצת oversized שחורה בבד כבד עם הדפס דיגיטלי באיכות גבוהה.',
    images: ['assets/images/products/paris.jpg', 'assets/images/products/paris-look.jpg'],
    ogImage: 'og-paris.png',
    colors: [
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL', soldOut: true },
    ],
    defaultSize: 'L',
    details: [
      '100% כותנה פרמיום, 240 גרם/מ"ר',
      'הדפס דיגיטלי איכותי שלא נסדק',
      'גזרת drop shoulder oversized',
      'כביסה הפוכה ב-30°C',
      'מסדרת Midnight in Paris',
    ],
  },
  'lotus': {
    id: 'lotus',
    name: 'Lotus',
    tag: 'New Drop',
    price: 159,
    description: 'הדפס "Lotus — Inner Peace" עם פרח לוטוס ורוד מינימליסטי. עיצוב שקט ונקי על חולצת oversized שחורה, לאוהבי הסטייל המאופק.',
    images: ['assets/images/products/lotus.jpg', 'assets/images/products/lotus-look.jpg'],
    ogImage: 'og-lotus.png',
    colors: [
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL' },
    ],
    defaultSize: 'M',
    details: [
      '100% כותנה, 240 גרם/מ"ר',
      'הדפס דיגיטלי איכותי',
      'גזרה oversized סטנדרטית',
      'כביסה הפוכה ב-30°C',
      'אריזת מתנה זמינה בצ׳קאאוט',
    ],
  },
  'eucalyptus': {
    id: 'eucalyptus',
    name: 'Eucalyptus',
    tag: 'New Drop',
    price: 165,
    description: 'הדפס "Eucalyptus — Harmony with Nature" עם פנדה על עץ אקליפטוס וכיתוב אנכי דרמטי. עיצוב עשיר ומלא נוכחות על חולצת oversized שחורה.',
    images: ['assets/images/products/eucalyptus.jpg', 'assets/images/products/eucalyptus-look.jpg'],
    ogImage: 'og-eucalyptus.png',
    colors: [
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S', soldOut: true },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL' },
    ],
    defaultSize: 'L',
    details: [
      '100% כותנה פרמיום, 250 גרם/מ"ר',
      'הדפס דיגיטלי איכותי שלא נסדק',
      'גזרת drop shoulder oversized',
      'כביסה הפוכה ב-30°C',
      'מסדרת Natural World',
    ],
  },
  'flamingo': {
    id: 'flamingo',
    name: 'Flamingo',
    tag: 'New Drop',
    price: 169,
    description: 'הדפס "Flamingo — Grace in Nature" עם פלמינגו והיביסקוס בגוונים חמים. עיצוב טרופי עשיר על חולצת oversized שחורה בבד כבד.',
    images: ['assets/images/products/flamingo.jpg', 'assets/images/products/flamingo-look.jpg'],
    ogImage: 'og-flamingo.png',
    colors: [
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL' },
    ],
    defaultSize: 'L',
    details: [
      '100% כותנה פרמיום, 250 גרם/מ"ר',
      'הדפס דיגיטלי איכותי שלא נסדק',
      'גזרת drop shoulder oversized',
      'כביסה הפוכה ב-30°C',
      'מסדרת Natural World',
    ],
  },
  'bloom': {
    id: 'bloom',
    name: 'BLOOM',
    tag: 'Hero Drop',
    price: 169,
    description: 'הפריט שהשיק את הקו — חולצת oversized עם הדפס BLOOM בלעדי. גזרה drop shoulder נדיבה, בד 250 גרם, הדפסה ישירה לבד שמחזיקה גם אחרי עשרות כביסות.',
    images: ['assets/images/products/bloom.jpg', 'assets/images/products/bloom-look.jpg'],
    ogImage: 'og-bloom.png',
    colors: [
      { name: 'לבן', hex: '#fff' },
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL' },
    ],
    defaultSize: 'L',
    details: [
      '100% כותנה פרמיום, 250 גרם/מ"ר',
      'הדפסה ישירה לבד (DTG) באיכות גבוהה',
      'גזרת drop shoulder oversized',
      'כביסה הפוכה ב-30°C',
      'מוצר ההשקה של המותג',
    ],
  },
  'sakur': {
    id: 'sakur',
    name: 'Sakur',
    tag: 'New Drop',
    price: 150,
    description: 'הדפס בלעדי בהשראת עץ הסאקורה. עיצוב נקי בחזית ועיצוב מלא בגב. בד רך עם הדפס דיגיטלי באיכות גבוהה שלא נסדק.',
    images: ['assets/images/products/sakur.jpg', 'assets/images/products/sakur-look.jpg'],
    ogImage: 'og-sakur.png',
    colors: [
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL', soldOut: true },
    ],
    defaultSize: 'M',
    details: [
      '100% כותנה, 240 גרם/מ"ר',
      'הדפס דיגיטלי איכותי',
      'גזרה oversized סטנדרטית',
      'כביסה הפוכה ב-30°C',
      'אריזת מתנה זמינה בצ׳קאאוט',
    ],
  },
};

window.PRODUCTS = PRODUCTS;
