// Shared product catalog. Both the homepage cards and the product page read from here.
const PRODUCTS = {
  'essential-tee': {
    id: 'essential-tee',
    name: 'Essential Oversized Tee',
    tag: 'Best Seller',
    price: 149,
    description: 'הקלאסיקה של OBSIZE. גזרה oversized נדיבה עם נפילה מושלמת על הכתפיים, בד כותנה כבד שמרגיש כמו חולצה אהובה כבר מהיום הראשון.',
    images: [],
    colors: [
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
      { name: 'לבן', hex: '#fff' },
      { name: 'אפור', hex: '#6b6b6b' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL', soldOut: true },
    ],
    defaultSize: 'L',
    details: [
      '100% כותנה פרמיום, 240 גרם/מ"ר',
      'גזרת drop shoulder אמיתית',
      'תפר כפול בקצוות לעמידות',
      'כביסה במכונה ב-30°C',
      'מיוצר בפורטוגל',
    ],
  },
  'heavy-drop': {
    id: 'heavy-drop',
    name: 'Heavy Drop Shoulder',
    tag: 'New Arrival',
    price: 179,
    description: 'גרסה כבדה יותר של ה-Essential. בד 280 גרם, מבנה שמחזיק צורה ונותן נוכחות בלי להיות נוקשה. הגזרה תוכננה לשכבות.',
    images: [],
    colors: [
      { name: 'נייבי', hex: '#1a1a2e' },
      { name: 'פחם', hex: '#2d2d2d' },
      { name: 'לבן', hex: '#fff' },
    ],
    sizes: [
      { label: 'S', soldOut: true },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL' },
    ],
    defaultSize: 'XL',
    details: [
      '100% כותנה כבדה, 280 גרם/מ"ר',
      'גזרת boxy עם כתף נופלת',
      'שרוול קצר רחב',
      'כביסה במכונה ב-30°C',
      'מתאים ללבישה בשכבות',
    ],
  },
  'washed-boxy': {
    id: 'washed-boxy',
    name: 'Washed Boxy Tee',
    tag: 'Limited',
    price: 199,
    description: 'כל יחידה עוברת תהליך שטיפה ייחודי שנותן לבד נגיעה רכה וגוון מעט דהוי. גזרה boxy קצרה ורחבה — חולצה שמרגישה כמו וינטג׳ מהיום הראשון.',
    images: [],
    colors: [
      { name: 'חום שטוף', hex: '#4a3728' },
      { name: 'אפור כהה', hex: '#3d3d3d' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL', soldOut: true },
      { label: 'XXL', soldOut: true },
    ],
    defaultSize: 'M',
    details: [
      '100% כותנה, 220 גרם/מ"ר',
      'שטיפה אבן לגוון וינטג׳ ייחודי',
      'כל יחידה שונה במעט בגוון',
      'כביסה בעדינות ב-30°C',
      'סדרה מוגבלת — 200 יחידות',
    ],
  },
  'bloom': {
    id: 'bloom',
    name: 'BLOOM',
    tag: 'Hero Drop',
    price: 169,
    description: 'הפריט שהשיק את הקו — חולצת oversized עם הדפס BLOOM בלעדי. גזרה drop shoulder נדיבה, בד 250 גרם, הדפסה ישירה לבד שמחזיקה גם אחרי עשרות כביסות.',
    images: ['העיצוב הייחודי של _BLOOM_.png'],
    ogImage: 'og-bloom.png',
    colors: [
      { name: 'לבן', hex: '#fff' },
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL' },
    ],
    defaultSize: 'L',
    details: [
      '100% כותנה פרמיום, 250 גרם/מ"ר',
      'הדפסה ישירה לבד (DTG) באיכות גבוהה',
      'גזרת drop shoulder oversized',
      'כביסה הפוכה ב-30°C',
      'מוצר ההשקה של המותג',
    ],
  },
  'sakur': {
    id: 'sakur',
    name: 'Sakur',
    tag: 'New Drop',
    price: 150,
    description: 'הדפס בלעדי בהשראת עץ הסאקורה. עיצוב נקי בחזית ועיצוב מלא בגב. בד רך עם הדפס דיגיטלי באיכות גבוהה שלא נסדק.',
    images: ['עיצוב סאקורה על חולצה שחורה.png'],
    ogImage: 'og-sakur.png',
    colors: [
      { name: 'שחור', hex: '#000', border: 'rgba(255,255,255,0.4)' },
    ],
    sizes: [
      { label: 'S' },
      { label: 'M' },
      { label: 'L' },
      { label: 'XL' },
      { label: 'XXL', soldOut: true },
    ],
    defaultSize: 'M',
    details: [
      '100% כותנה, 240 גרם/מ"ר',
      'הדפס דיגיטלי איכותי',
      'גזרה oversized סטנדרטית',
      'כביסה הפוכה ב-30°C',
      'אריזת מתנה זמינה בצ׳קאאוט',
    ],
  },
};

window.PRODUCTS = PRODUCTS;
